name: CI for Python and Flask

on:
  push:
    branches:
      - '*'  # Trigger the pipeline on any branch commit
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Ensures Python is installed

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r server/requirements.txt
          pip install pytest pytest-flask
        displayName: 'Install Flask dependencies'

      - name: Run Flask tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)/server  # Set PYTHONPATH to include the server folder
          pytest server/tests/ --junitxml=junit/test-results-flask.xml
        displayName: 'Run Flask tests'

      - name: Publish test results
        if: always()  # Run this step even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: '**/junit/test-results-*.xml'