trigger:
  branches:
    include:
      - '*'  # Trigger on any branch commit

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

- script: |
    python -m venv venv
    if [ ! -d "venv" ]; then
      echo "Virtual environment creation failed"
      exit 1
    fi
    source venv/bin/activate
    pip install -r ./server/requirements.txt
  displayName: 'Install Flask dependencies'

- script: |
    source venv/bin/activate
    export PYTHONPATH=$(pwd)/server
    pytest server/tests/ --junitxml=junit/test-results-flask.xml
  displayName: 'Run Flask tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit/test-results-*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'