trigger:
  branches:
    include:
      - '*'  # Trigger the pipeline on any branch commit

pool:
  vmImage: 'ubuntu-latest'

steps:
# Python setup for Flask tests
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r server/requirements.txt
    pip install pytest pytest-flask
  displayName: 'Install Flask dependencies'

- script: |
    set -e  # Exit on error
    source venv/bin/activate
    export PYTHONPATH=$(pwd)
    mkdir -p junit  # Ensure the junit directory exists
    pytest server/tests/ --junitxml=junit/test-results-flask.xml
  displayName: 'Run Flask tests'

# Node.js setup for React tests
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # or the Node.js version you're using
    checkLatest: true

# Test for React
- script: |
    set -e  # Exit on error
    cd client  # Navigate to the client directory where your React app is located
    npm install
    npm test -- --coverage --ci --watchAll=false  # Run tests with coverage in CI mode
  displayName: 'Run React tests'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit/test-results-*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'
