trigger:
  branches:
    include:
      - '*'  # Trigger the pipeline on any branch commit

pool:
  vmImage: 'ubuntu-latest'

steps:
# Python setup for Flask tests
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r server/requirements.txt
    pip install pytest pytest-flask
  displayName: 'Install Flask dependencies'

- script: |
    source venv/bin/activate
    export PYTHONPATH=$(pwd)
    pytest server/tests/ --junitxml=junit/test-results-flask.xml
  displayName: 'Juhil Flask tests'

# Node.js setup for React tests
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # or the Node.js version you're using
    checkLatest: true

# Test for React
#- script: |
#    cd client
#    npm install
#    npm run test -- --coverage --ci --watchAll=false
#  displayName: 'Juhil React tests'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit/test-results-*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'