trigger:
  branches:
    include:
      - '*'  # This triggers the pipeline on any branch commit

pool:
  vmImage: 'ubuntu-latest'

# Backend Python Steps
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you want to use
    addToPath: true

- script: |
    echo "Running Backend Tests by Joseph Jello"
    python -m venv venv
    source venv/bin/activate  # For Windows, use `venv\Scripts\activate`
    pip install -r server/requirements.txt
    pip install pytest pytest-flask
  displayName: 'Install Python dependencies'

- script: |
    echo "Executing Backend Tests - Joseph Jello"
    source venv/bin/activate  # For Windows, use `venv\Scripts\activate`
    export PYTHONPATH=$(pwd)  # Add the root directory to PYTHONPATH
    pytest server/tests/ --junitxml=junit/test-results.xml  # Explicitly mention the tests directory
  displayName: 'Run backend tests'

# Frontend Node.js Steps
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Use Node.js version 14.x
  displayName: 'Install Node.js'

- script: |
    echo "Running Frontend Tests by Joseph Jello"
    cd client  # Navigate to the frontend directory
    npm install
    npm test -- --ci --reporters=jest-junit --outputFile=results/junit/test-results.xml
  displayName: 'Run frontend tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'results/junit/test-results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'

- script: |
    echo "Pipeline completed by Joseph Jello"
  displayName: 'Completion Log'
