trigger:
  branches:
    include:
      - '*'  # Set to your default branch

pool:
  vmImage: 'ubuntu-latest'  # You can also use windows-latest if you prefer

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify your Python version
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate  # Use venv\Scripts\activate if on Windows
    pip install -r server/requirements.txt  # Install your Flask app dependencies
    pip install pytest pytest-flask         # Install testing dependencies
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate  # Activate virtual environment (or venv\Scripts\activate on Windows)
    pytest tests/ --junitxml=junit/test-results.xml  # Run tests and output results in JUnit format
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit/test-results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'