trigger:
  branches:
    include:
      - '*'  # This triggers the pipeline on any branch commit

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you want to use
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate  # For Windows, use `venv\Scripts\activate`
    pip install -r server/requirements.txt
    pip install pytest pytest-flask
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate  # For Windows, use `venv\Scripts\activate`
    export PYTHONPATH=$(pwd)  # Add the root directory to PYTHONPATH
    pytest tests/ --junitxml=junit/test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit/test-results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'