name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'  # Run on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r ./server/requirements.txt
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.7/x64

      - name: Run Flask tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)/server
          pytest server/tests/ --junitxml=junit/test-results-flask.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: junit/test-results-*.xml