name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'  # Run on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update and Upgrade python-virtualenv
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-virtualenv

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Confirm Python version and location
        run: |
          python --version
          which python

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          if [ ! -d "venv" ]; then
            echo "Virtual environment creation failed"
            exit 1
          fi
          ls -la  # List directory to check venv created
          source venv/bin/activate
          pip install -r ./server/requirements.txt

      - name: Run Flask tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)/server
          pytest server/tests/ --junitxml=junit/test-results-flask.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: junit/test-results-*.xml